---
title: "betaNB: Example Using the BetaNB Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-2022
  @Efron-Tibshirani-1993
vignette: >
  %\VignetteIndexEntry{betaNB: Example Using the BetaNB Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



In this example, a multiple regression model is fitted
using program quality ratings (`QUALITY`) as the regressand/outcome variable
and number of published articles attributed to the program faculty members (`NARTIC`),
percent of faculty members holding research grants (`PCTGRT`), and
percentage of program graduates who received support (`PCTSUPP`) as regressor/predictor variables
using a data set from 1982 ratings of 46 doctoral programs in psychology in the USA (National Research Council, 1982).
Confidence intervals for the standardized regression coefficients are generated
using the `BetaNB()` function from the `betaNB` package.


``` r
library(betaNB)
```




``` r
df <- betaNB::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Nonparametric Bootstrap


``` r
nb <- NB(object)
```

### Standardized Regression Slopes


``` r
out <- BetaNB(nb, alpha = 0.05)
```

## Methods

### summary

Summary of the results of `BetaNB()`.

#### Percentile Confidence Intervals


``` r
summary(out, type = "pc")
#> Call:
#> BetaNB(object = nb, alpha = 0.05)
#> 
#> Standardized regression slopes
#> type = "pc"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.4951 0.0730 5000 0.3496 0.6348
#> PCTGRT  0.3915 0.0768 5000 0.2394 0.5418
#> PCTSUPP 0.2632 0.0801 5000 0.0964 0.4156
```

#### Bias Corrected Confidence Intervals


``` r
summary(out, type = "bc")
#> Call:
#> BetaNB(object = nb, alpha = 0.05)
#> 
#> Standardized regression slopes
#> type = "bc"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.4951 0.0730 5000 0.3484 0.6324
#> PCTGRT  0.3915 0.0768 5000 0.2479 0.5529
#> PCTSUPP 0.2632 0.0801 5000 0.0953 0.4138
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
summary(out, type = "bca")
#> Call:
#> BetaNB(object = nb, alpha = 0.05)
#> 
#> Standardized regression slopes
#> type = "bca"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.4951 0.0730 5000 0.3492 0.6338
#> PCTGRT  0.3915 0.0768 5000 0.2542 0.5581
#> PCTSUPP 0.2632 0.0801 5000 0.0876 0.4072
```

### coef

Return the vector of estimates.


``` r
coef(out)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4951451 0.3914887 0.2632477
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(out)
#>               NARTIC       PCTGRT      PCTSUPP
#> NARTIC   0.005325721 -0.003222684 -0.001802658
#> PCTGRT  -0.003222684  0.005897218 -0.002090162
#> PCTSUPP -0.001802658 -0.002090162  0.006414468
```

### confint

Return confidence intervals.

#### Percentile Confidence Intervals


``` r
confint(out, level = 0.95, type = "pc")
#>              2.5 %    97.5 %
#> NARTIC  0.34963160 0.6347988
#> PCTGRT  0.23942064 0.5418251
#> PCTSUPP 0.09643629 0.4155640
```

#### Bias Corrected Confidence Intervals


``` r
confint(out, level = 0.95, type = "bc")
#>              2.5 %    97.5 %
#> NARTIC  0.34837842 0.6323539
#> PCTGRT  0.24787748 0.5529307
#> PCTSUPP 0.09527074 0.4138054
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
confint(out, level = 0.95, type = "bca")
#>              2.5 %    97.5 %
#> NARTIC  0.34920196 0.6338228
#> PCTGRT  0.25417418 0.5581050
#> PCTSUPP 0.08757402 0.4072147
```

## References
