---
title: "betaNB: Example Using the DeltaRSqNB Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-2022
  @Efron-Tibshirani-1993
vignette: >
  %\VignetteIndexEntry{betaNB: Example Using the DeltaRSqNB Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



Confidence intervals for
improvement in R-squared
are generated using
the `DeltaRSqNB()` function from the `betaNB` package.
In this example,
we use the data set and the model used in
[betaNB: Example Using the BetaNB Function](example-beta-nb.html).


``` r
library(betaNB)
```




``` r
df <- betaNB::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Nonparametric Bootstrap


``` r
nb <- NB(object)
```

### Improvement in R-squared

#### Normal-Theory Approach


``` r
out <- DeltaRSqNB(nb, alpha = 0.05)
```

## Methods

### summary

Summary of the results of `DeltaRSqNB()`.

#### Percentile Confidence Intervals


``` r
summary(out, type = "pc")
#> Call:
#> DeltaRSqNB(object = nb, alpha = 0.05)
#> 
#> Improvement in R-squared
#> type = "pc"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.1859 0.0590 5000 0.0840 0.3113
#> PCTGRT  0.1177 0.0482 5000 0.0364 0.2241
#> PCTSUPP 0.0569 0.0342 5000 0.0079 0.1383
```

#### Bias Corrected Confidence Intervals


``` r
summary(out, type = "bc")
#> Call:
#> DeltaRSqNB(object = nb, alpha = 0.05)
#> 
#> Improvement in R-squared
#> type = "bc"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.1859 0.0590 5000 0.0910 0.3242
#> PCTGRT  0.1177 0.0482 5000 0.0435 0.2402
#> PCTSUPP 0.0569 0.0342 5000 0.0094 0.1463
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
summary(out, type = "bca")
#> Call:
#> DeltaRSqNB(object = nb, alpha = 0.05)
#> 
#> Improvement in R-squared
#> type = "bca"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.1859 0.0590 5000 0.0943 0.3336
#> PCTGRT  0.1177 0.0482 5000 0.0474 0.2515
#> PCTSUPP 0.0569 0.0342 5000 0.0083 0.1422
```

### coef

Return the vector of estimates.


``` r
coef(out)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.1858925 0.1176542 0.0568722
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(out)
#>                NARTIC        PCTGRT       PCTSUPP
#> NARTIC   0.0034784277 -0.0001978768 -0.0002350681
#> PCTGRT  -0.0001978768  0.0023233655 -0.0002253087
#> PCTSUPP -0.0002350681 -0.0002253087  0.0011725129
```

### confint

Return confidence intervals.

#### Percentile Confidence Intervals


``` r
confint(out, level = 0.95, type = "pc")
#>               2.5 %    97.5 %
#> NARTIC  0.084004807 0.3113348
#> PCTGRT  0.036417320 0.2240972
#> PCTSUPP 0.007893907 0.1382997
```

#### Bias Corrected Confidence Intervals


``` r
confint(out, level = 0.95, type = "bc")
#>               2.5 %    97.5 %
#> NARTIC  0.091009535 0.3241850
#> PCTGRT  0.043531621 0.2401771
#> PCTSUPP 0.009436577 0.1463385
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
confint(out, level = 0.95, type = "bca")
#>               2.5 %    97.5 %
#> NARTIC  0.094309326 0.3335986
#> PCTGRT  0.047407540 0.2515120
#> PCTSUPP 0.008328542 0.1421619
```

## References
