---
title: "betaNB: Example Using the SCorNB Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-2022
  @Efron-Tibshirani-1993
vignette: >
  %\VignetteIndexEntry{betaNB: Example Using the SCorNB Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



Confidence intervals for
semipartial correlation coefficients
are generated using
the `SCorNB()` function from the `betaNB` package.
In this example,
we use the data set and the model used in
[betaNB: Example Using the BetaNB Function](example-beta-nb.html).


``` r
library(betaNB)
```




``` r
df <- betaNB::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Nonparametric Bootstrap


``` r
nb <- NB(object)
```

### Semipartial Correlation Coefficients

#### Normal-Theory Approach


``` r
out <- SCorNB(nb, alpha = 0.05)
```

## Methods

### summary

Summary of the results of `SCorNB()`.

#### Percentile Confidence Intervals


``` r
summary(out, type = "pc")
#> Call:
#> SCorNB(object = nb, alpha = 0.05)
#> 
#> Semipartial correlations
#> type = "pc"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.4312 0.0704 5000 0.2848 0.5579
#> PCTGRT  0.3430 0.0726 5000 0.1925 0.4770
#> PCTSUPP 0.2385 0.0719 5000 0.0886 0.3682
```

#### Bias Corrected Confidence Intervals


``` r
summary(out, type = "bc")
#> Call:
#> SCorNB(object = nb, alpha = 0.05)
#> 
#> Semipartial correlations
#> type = "bc"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.4312 0.0704 5000 0.3009 0.5739
#> PCTGRT  0.3430 0.0726 5000 0.2116 0.4998
#> PCTSUPP 0.2385 0.0719 5000 0.0991 0.3817
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
summary(out, type = "bca")
#> Call:
#> SCorNB(object = nb, alpha = 0.05)
#> 
#> Semipartial correlations
#> type = "bca"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.4312 0.0704 5000 0.3069 0.5826
#> PCTGRT  0.3430 0.0726 5000 0.2204 0.5156
#> PCTSUPP 0.2385 0.0719 5000 0.0966 0.3760
```

### coef

Return the vector of estimates.


``` r
coef(out)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4311525 0.3430075 0.2384789
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(out)
#>                NARTIC        PCTGRT       PCTSUPP
#> NARTIC   0.0049582857 -0.0005134860 -0.0006315653
#> PCTGRT  -0.0005134860  0.0052637920 -0.0008617772
#> PCTSUPP -0.0006315653 -0.0008617772  0.0051670152
```

### confint

Return confidence intervals.

#### Percentile Confidence Intervals


``` r
confint(out, level = 0.95, type = "pc")
#>              2.5 %    97.5 %
#> NARTIC  0.28484030 0.5579198
#> PCTGRT  0.19254786 0.4770164
#> PCTSUPP 0.08855684 0.3681861
```

#### Bias Corrected Confidence Intervals


``` r
confint(out, level = 0.95, type = "bc")
#>              2.5 %    97.5 %
#> NARTIC  0.30088593 0.5738620
#> PCTGRT  0.21160148 0.4998354
#> PCTSUPP 0.09908042 0.3816574
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
confint(out, level = 0.95, type = "bca")
#>              2.5 %    97.5 %
#> NARTIC  0.30686766 0.5825502
#> PCTGRT  0.22041652 0.5156411
#> PCTSUPP 0.09664894 0.3760336
```

## References
