---
title: "betaNB: Example Using the PCorNB Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-2022
  @Efron-Tibshirani-1993
vignette: >
  %\VignetteIndexEntry{betaNB: Example Using the PCorNB Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



Confidence intervals for
squared partial correlation coefficients
are generated using
the `PCorNB()` function from the `betaNB` package.
In this example,
we use the data set and the model used in
[betaNB: Example Using the BetaNB Function](example-beta-nb.html).


``` r
library(betaNB)
```




``` r
df <- betaNB::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Nonparametric Bootstrap


``` r
nb <- NB(object)
```

### Squared Partial Correlation Coefficients

#### Normal-Theory Approach


``` r
out <- PCorNB(nb, alpha = 0.05)
```

## Methods

### summary

Summary of the results of `PCorNB()`.

#### Percentile Confidence Intervals


``` r
summary(out, type = "pc")
#> Call:
#> PCorNB(object = nb, alpha = 0.05)
#> 
#> Squared partial correlations
#> type = "pc"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.4874 0.0989 5000 0.2878 0.6717
#> PCTGRT  0.3757 0.1086 5000 0.1610 0.5813
#> PCTSUPP 0.2254 0.1143 5000 0.0426 0.4779
```

#### Bias Corrected Confidence Intervals


``` r
summary(out, type = "bc")
#> Call:
#> PCorNB(object = nb, alpha = 0.05)
#> 
#> Squared partial correlations
#> type = "bc"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.4874 0.0989 5000 0.2655 0.6563
#> PCTGRT  0.3757 0.1086 5000 0.1581 0.5787
#> PCTSUPP 0.2254 0.1143 5000 0.0449 0.4803
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
summary(out, type = "bca")
#> Call:
#> PCorNB(object = nb, alpha = 0.05)
#> 
#> Squared partial correlations
#> type = "bca"
#>            est     se    R   2.5%  97.5%
#> NARTIC  0.4874 0.0989 5000 0.2660 0.6571
#> PCTGRT  0.3757 0.1086 5000 0.1625 0.5831
#> PCTSUPP 0.2254 0.1143 5000 0.0285 0.4612
```

### coef

Return the vector of estimates.


``` r
coef(out)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4874382 0.3757383 0.2253739
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(out)
#>              NARTIC       PCTGRT      PCTSUPP
#> NARTIC  0.009779647 0.0017525137 0.0021004694
#> PCTGRT  0.001752514 0.0117862386 0.0008994053
#> PCTSUPP 0.002100469 0.0008994053 0.0130536522
```

### confint

Return confidence intervals.

#### Percentile Confidence Intervals


``` r
confint(out, level = 0.95, type = "pc")
#>              2.5 %    97.5 %
#> NARTIC  0.28783106 0.6716504
#> PCTGRT  0.16103524 0.5813309
#> PCTSUPP 0.04260807 0.4779286
```

#### Bias Corrected Confidence Intervals


``` r
confint(out, level = 0.95, type = "bc")
#>              2.5 %    97.5 %
#> NARTIC  0.26548716 0.6562662
#> PCTGRT  0.15807492 0.5786526
#> PCTSUPP 0.04490979 0.4802874
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
confint(out, level = 0.95, type = "bca")
#>              2.5 %    97.5 %
#> NARTIC  0.26601340 0.6570524
#> PCTGRT  0.16248560 0.5831266
#> PCTSUPP 0.02848846 0.4612253
```

## References
