---
title: "betaNB: Example Using the DiffBetaNB Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-2022
  @Efron-Tibshirani-1993
vignette: >
  %\VignetteIndexEntry{betaNB: Example Using the DiffBetaNB Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



Confidence intervals for
differences of standardized regression slopes
are generated using
the `DiffBetaNB()` function from the `betaNB` package.
In this example,
we use the data set and the model used in
[betaNB: Example Using the BetaNB Function](example-beta-nb.html).


``` r
library(betaNB)
```




``` r
df <- betaNB::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Nonparametric Bootstrap


``` r
nb <- NB(object)
```

### Differences of Standardized Regression Slopes

#### Normal-Theory Approach


``` r
out <- DiffBetaNB(nb, alpha = 0.05)
```

## Methods

### summary

Summary of the results of `DiffBetaNB()`.

#### Percentile Confidence Intervals


``` r
summary(out, type = "pc")
#> Call:
#> DiffBetaNB(object = nb, alpha = 0.05)
#> 
#> Differences of standardized regression slopes
#> type = "pc"
#>                   est     se    R    2.5%  97.5%
#> NARTIC-PCTGRT  0.1037 0.1304 5000 -0.1524 0.3719
#> NARTIC-PCTSUPP 0.2319 0.1249 5000 -0.0005 0.4816
#> PCTGRT-PCTSUPP 0.1282 0.1291 5000 -0.1152 0.3938
```

#### Bias Corrected Confidence Intervals


``` r
summary(out, type = "bc")
#> Call:
#> DiffBetaNB(object = nb, alpha = 0.05)
#> 
#> Differences of standardized regression slopes
#> type = "bc"
#>                   est     se    R    2.5%  97.5%
#> NARTIC-PCTGRT  0.1037 0.1304 5000 -0.1488 0.3755
#> NARTIC-PCTSUPP 0.2319 0.1249 5000  0.0007 0.4826
#> PCTGRT-PCTSUPP 0.1282 0.1291 5000 -0.1107 0.3969
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
summary(out, type = "bca")
#> Call:
#> DiffBetaNB(object = nb, alpha = 0.05)
#> 
#> Differences of standardized regression slopes
#> type = "bca"
#>                   est     se    R    2.5%  97.5%
#> NARTIC-PCTGRT  0.1037 0.1304 5000 -0.1497 0.3741
#> NARTIC-PCTSUPP 0.2319 0.1249 5000 -0.0017 0.4801
#> PCTGRT-PCTSUPP 0.1282 0.1291 5000 -0.1019 0.4101
```

### coef

Return the vector of estimates.


``` r
coef(out)
#>  NARTIC-PCTGRT NARTIC-PCTSUPP PCTGRT-PCTSUPP 
#>      0.1036564      0.2318974      0.1282410
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(out)
#>                NARTIC-PCTGRT NARTIC-PCTSUPP PCTGRT-PCTSUPP
#> NARTIC-PCTGRT    0.017003220    0.007966227   -0.009036993
#> NARTIC-PCTSUPP   0.007966227    0.015603755    0.007637528
#> PCTGRT-PCTSUPP  -0.009036993    0.007637528    0.016674521
```

### confint

Return confidence intervals.

#### Percentile Confidence Intervals


``` r
confint(out, level = 0.95, type = "pc")
#>                        2.5 %    97.5 %
#> NARTIC-PCTGRT  -0.1524165651 0.3718869
#> NARTIC-PCTSUPP -0.0004714769 0.4816004
#> PCTGRT-PCTSUPP -0.1151968501 0.3938071
```

#### Bias Corrected Confidence Intervals


``` r
confint(out, level = 0.95, type = "bc")
#>                        2.5 %    97.5 %
#> NARTIC-PCTGRT  -0.1488200605 0.3755089
#> NARTIC-PCTSUPP  0.0007051056 0.4826249
#> PCTGRT-PCTSUPP -0.1106879635 0.3968648
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
confint(out, level = 0.95, type = "bca")
#>                       2.5 %    97.5 %
#> NARTIC-PCTGRT  -0.149682071 0.3741300
#> NARTIC-PCTSUPP -0.001676892 0.4801475
#> PCTGRT-PCTSUPP -0.101937845 0.4100872
```

## References
