---
title: "betaNB: Example Using the RSqNB Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-2022
  @Efron-Tibshirani-1993
vignette: >
  %\VignetteIndexEntry{betaNB: Example Using the RSqNB Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



Confidence intervals for
multiple correlation coefficients
are generated using
the `RSqNB()` function from the `betaNB` package.
In this example,
we use the data set and the model used in
[betaNB: Example Using the BetaNB Function](example-beta-nb.html).


``` r
library(betaNB)
```




``` r
df <- betaNB::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Nonparametric Bootstrap


``` r
nb <- NB(object)
```

### Multiple Correlation Coefficients

#### Normal-Theory Approach


``` r
out <- RSqNB(nb, alpha = 0.05)
```

## Methods

### summary

Summary of the results of `RSqNB()`.

#### Percentile Confidence Intervals


``` r
summary(out, type = "pc")
#> Call:
#> RSqNB(object = nb, alpha = 0.05)
#> 
#> R-squared and adjusted R-squared
#> type = "pc"
#>        est     se    R   2.5%  97.5%
#> rsq 0.8045 0.0530 5000 0.6937 0.8976
#> adj 0.7906 0.0568 5000 0.6719 0.8903
```

#### Bias Corrected Confidence Intervals


``` r
summary(out, type = "bc")
#> Call:
#> RSqNB(object = nb, alpha = 0.05)
#> 
#> R-squared and adjusted R-squared
#> type = "bc"
#>        est     se    R   2.5%  97.5%
#> rsq 0.8045 0.0530 5000 0.6497 0.8820
#> adj 0.7906 0.0568 5000 0.6247 0.8736
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
summary(out, type = "bca")
#> Call:
#> RSqNB(object = nb, alpha = 0.05)
#> 
#> R-squared and adjusted R-squared
#> type = "bca"
#>        est     se    R   2.5%  97.5%
#> rsq 0.8045 0.0530 5000 0.6423 0.8801
#> adj 0.7906 0.0568 5000 0.6167 0.8716
```

### coef

Return the vector of estimates.


``` r
coef(out)
#>       rsq       adj 
#> 0.8045263 0.7905638
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(out)
#>             rsq         adj
#> rsq 0.002813317 0.003014269
#> adj 0.003014269 0.003229574
```

### confint

Return confidence intervals.

#### Percentile Confidence Intervals


``` r
confint(out, level = 0.95, type = "pc")
#>         2.5 %    97.5 %
#> rsq 0.6937304 0.8976445
#> adj 0.6718540 0.8903334
```

#### Bias Corrected Confidence Intervals


``` r
confint(out, level = 0.95, type = "bc")
#>         2.5 %    97.5 %
#> rsq 0.6497357 0.8820266
#> adj 0.6247168 0.8735999
```

#### Bias Corrected and Accelerated Confidence Intervals


``` r
confint(out, level = 0.95, type = "bca")
#>         2.5 %    97.5 %
#> rsq 0.6422516 0.8801332
#> adj 0.6166982 0.8715713
```

## References
